### ISSUE TITLE
Versions for Firefox or Safari

### ISSUE THREAD

**Issue by markmark1** [njuljsong/wsjUnblock#4]

**Comment by strafer** [comment]
I'd love to have a version of this for Safari and Firefox extensions. Is there a great technical difference in the extensions for these other browsers?

**Comment by strafer** [comment]
I was able to create a working Safari extension in 10 minutes using the instructions on this page (http://www.macworld.com/article/1156941/business/safariextension.html). Granted, that's the simple way of creating a Safari extension. Using Xcode, you can do a lot more. 

However, so far, the extension seems to be working. The only drawback is that you need a Safari Extension Certificate if you want the extension to load automatically every time you start Safari. That requires an Apple Developer account which costs, I believe, $99/year.

As it stands now, you have to re-install the extension using the Safari extension builder each time you start Safari. It's a minor annoyance.

**Comment by strafer** [comment]
Let me clarify. I just added the css portion of this plugin to a Safari plugin because I wanted to access the NY Times cooking site in Safari. 

This Chrome plugin uses chrome.webRequest functions in javascript to work around the WSJ and NYTimes paywalls. Those won't work in Safari extensions and would need to be adapted. I found a StackExchange post about finding a Safari equivalent of chrome.webRequest functions:
https://stackoverflow.com/questions/28057058/writing-an-equivalent-to-chromes-onbeforerequest-in-a-safari-extension

**Comment by njuljsong** [comment]
@markmark1 @strafer : thanks for the info and efforts to try to create Firefox and Safari version.

May I ask why bother doing this? Chrome browser can be used in both Mac and Windows desktop machines, it provides arguably the best user experience. Safari can only be used in Mac. Firefox has no obvious advantage to chrome. I have no motivation to make this extension work for Firefox or Safari.

**Comment by markmark1** [comment]
Chrome is barely usable on air and heats up and crashes the computer frequently   
  
Safari is light and fast and ffox is better than chrome on most aspects
  
Hence    can you please spearhead an effort to make extensions for Safari and Firefox as well as it’s a Videos for the extension
  

  
  

  
  
>

**Comment by markmark1** [comment]
So I have stopped    using chrome   
  

  
  

  
  
>

**Comment by strafer** [comment]
@njuljsong: I agree. There is no reason for you to make a Safari or Firefox version of this plugin. Perhaps someone with an Apple Developer's account will incorporate you code into a Safari or Firefox plugin.

As I mentioned earlier, I was able to package your CSS code into a Safari extension for myself. It seems to work so far, so I'm happy to have a solution for both Safari and Chrome.

I use both Safari and Chrome. But Safari is my main browser, mostly because it's much more energy efficient on macOS than Chrome is. So my laptop battery lasts significantly longer using Safari.

Thanks again for getting the plugin to work with the NY Times Cooking site.

**Comment by njuljsong** [comment]
Safari is much more energy efficient than Chrome so far. That is a valid point. But the developer license thing make it not worth it to create add-on for Safari.

So I will close the case.
